### ISSUE TITLE
support other files/languages

### ISSUE THREAD

**Issue by ctf0** [Ara225/console-log-linter#2]
atm its mostly about js files, but as we are using a regex maybe it could be extended to other languages too.

**Comment by Ara225** [comment]
Hi, 
I've thought of it, but not really the implementation details yet. I think it would be ideal to have the regexes for each language activate only on files of that language, but that might be a pain, rather than lumping them together.

**Comment by ctf0** [comment]
it will need some work indeed but its doable 🏆

**Comment by Ara225** [comment]
Hi,
I've implemented that, published as a separate extension as you can't rename extentions
